//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eHMISEntities : DbContext
    {
        public eHMISEntities()
            : base("name=eHMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EthEhmis_HMISValue> EthEhmis_HMISValue { get; set; }
        public virtual DbSet<EthioHIMS_QuarterHPDiseaseView> EthioHIMS_QuarterHPDiseaseView { get; set; }
        public virtual DbSet<EthioHIMS_QuarterIPDDiseaseView> EthioHIMS_QuarterIPDDiseaseView { get; set; }
        public virtual DbSet<EthioHIMS_QuarterOPDDiseaseView4> EthioHIMS_QuarterOPDDiseaseView4 { get; set; }
        public virtual DbSet<EthioHIMS_ServiceDataElementsNew> EthioHIMS_ServiceDataElementsNew { get; set; }
        public virtual DbSet<EthEhmis_HMISDenominator> EthEhmis_HMISDenominator { get; set; }
        public virtual DbSet<v_EthEhmis_AllFacilityWithIDNew> v_EthEhmis_AllFacilityWithIDNew { get; set; }
        public virtual DbSet<EthEhmis_AllFacilityWithID> EthEhmis_AllFacilityWithID { get; set; }
        public virtual DbSet<EthEHMIS_ImportedFiles> EthEHMIS_ImportedFiles { get; set; }
        public virtual DbSet<UserDashboard> UserDashboards { get; set; }
    }
}
