//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eHMIS_memoryoptimizedtable
    {
        public int ValueID { get; set; }
        public Nullable<int> LabelID { get; set; }
        public Nullable<int> DataEleClass { get; set; }
        public Nullable<int> FederalID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> WoredaID { get; set; }
        public string LocationID { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> FACILITTYPE { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<bool> Editable { get; set; }
    }
}
