//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthEhmis_AllFacilityWithID
    {
        public long DistrictId { get; set; }
        public int FacilityTypeId { get; set; }
        public string FacilityTypeName { get; set; }
        public string HMISCode { get; set; }
        public string FacilityName { get; set; }
        public Nullable<int> HealthCenterID { get; set; }
        public string HealthCenterName { get; set; }
        public Nullable<long> WoredaId { get; set; }
        public string WoredaName { get; set; }
        public Nullable<long> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string ReportingRegionName { get; set; }
        public string ReportingAdminSite { get; set; }
        public Nullable<long> ReportingDistrictId { get; set; }
        public Nullable<int> reportingFacilityTypeId { get; set; }
    }
}
