//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthEhmis_HMISDenominator
    {
        public int DenominatorID { get; set; }
        public string DenominatorName { get; set; }
        public Nullable<bool> Healthpost { get; set; }
        public Nullable<bool> HealthCenter { get; set; }
        public Nullable<bool> Hospital { get; set; }
        public Nullable<bool> WoredaHO { get; set; }
        public Nullable<bool> ZonalHD { get; set; }
        public Nullable<bool> RegionalHB { get; set; }
        public Nullable<bool> FMOH { get; set; }
        public string Period { get; set; }
    }
}
