//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthioHIMS_ServiceDataElementsNew
    {
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> LabelID { get; set; }
        public string SNO { get; set; }
        public string ActivityHP { get; set; }
        public string ActivityHC { get; set; }
        public string ActivityWorHO { get; set; }
        public string FullDescription { get; set; }
        public string AnalysisDescription { get; set; }
        public string GroupName { get; set; }
        public string ShortActivityDesc { get; set; }
        public Nullable<decimal> Lessthan { get; set; }
        public Nullable<decimal> Greaterthan { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> LessConstraintId { get; set; }
        public Nullable<int> GreaterConstraintId { get; set; }
        public Nullable<int> VerticalSumID { get; set; }
        public Nullable<int> PeriodType { get; set; }
        public Nullable<int> AggregationType { get; set; }
        public Nullable<bool> Readonly { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<bool> HP { get; set; }
        public Nullable<bool> HC { get; set; }
        public Nullable<bool> HCHP { get; set; }
        public Nullable<bool> Hospital { get; set; }
        public Nullable<bool> WHO { get; set; }
        public Nullable<bool> ZHD { get; set; }
        public Nullable<bool> RHB { get; set; }
        public Nullable<bool> FMOH { get; set; }
        public Nullable<bool> Private { get; set; }
        public string Description { get; set; }
        public Nullable<bool> quarterTitleHC { get; set; }
        public Nullable<bool> quarterTitleHP { get; set; }
        public Nullable<bool> isArtPastValidate { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
    }
}
