//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDashboard
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string dashboardSpec { get; set; }
        public string dataSQL { get; set; }
        public string title { get; set; }
    }
}
