/*
 * 
 * Copyright © 2006-2017 TenaCareeHMIS  software, by The Administrators of the Tulane Educational Fund, 
 * dba Tulane University, Center for Global Health Equity is distributed under the GNU General Public License(GPL).
 * All rights reserved.

 * This file is part of TenaCareeHMIS
 * TenaCareeHMIS is free software: 
 * 
 * you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation, 
 * version 3 of the License, or any later version.
 * TenaCareeHMIS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.See the GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along with TenaCareeHMIS.  
 * If not, see http://www.gnu.org/licenses/.    
 * 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_EthEhmis_AllFacilityWithID
    {
        public int DistrictId { get; set; }
        public Nullable<byte> FacilityTypeId { get; set; }
        public string FacilityTypeName { get; set; }
        public string HMISCode { get; set; }
        public string FacilityName { get; set; }
        public int HealthCenterID { get; set; }
        public string HealthCenterName { get; set; }
        public int WoredaId { get; set; }
        public string WoredaName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZONENAME { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string ReportingRegionName { get; set; }
        public string ReportingAdminSite { get; set; }
        public Nullable<int> ReportingDistrictId { get; set; }
        public int reportingFacilityTypeId { get; set; }
    }
}
