/*
 * 
 * Copyright © 2006-2017 TenaCareeHMIS  software, by The Administrators of the Tulane Educational Fund, 
 * dba Tulane University, Center for Global Health Equity is distributed under the GNU General Public License(GPL).
 * All rights reserved.

 * This file is part of TenaCareeHMIS
 * TenaCareeHMIS is free software: 
 * 
 * you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation, 
 * version 3 of the License, or any later version.
 * TenaCareeHMIS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.See the GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along with TenaCareeHMIS.  
 * If not, see http://www.gnu.org/licenses/.    
 * 
 * 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHMISWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eHMIS_memoryoptimizedtable
    {
        //public int ValueID { get; set; }
        //public Nullable<int> LabelID { get; set; }
        //public Nullable<int> DataEleClass { get; set; }
        //public Nullable<int> FederalID { get; set; }
        //public Nullable<int> RegionID { get; set; }
        //public Nullable<int> ZoneID { get; set; }
        //public Nullable<int> WoredaID { get; set; }
        //public string LocationID { get; set; }
        //public Nullable<int> Week { get; set; }
        //public Nullable<int> Month { get; set; }
        //public Nullable<int> Quarter { get; set; }
        //public Nullable<int> Year { get; set; }
        //public Nullable<decimal> Value { get; set; }
        //public Nullable<int> Level { get; set; }
        //public Nullable<int> FACILITTYPE { get; set; }
        //public Nullable<System.DateTime> DateEntered { get; set; }
        //public Nullable<bool> Editable { get; set; }
    }
}
